// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBunTdrli6tJGCCYCHf-UPvfbXFRv3Ybw8',
    appId: '1:652753902156:web:0360c9c923782ffa8bb2e9',
    messagingSenderId: '652753902156',
    projectId: 'nusliving-a83dc',
    authDomain: 'nusliving-a83dc.firebaseapp.com',
    storageBucket: 'nusliving-a83dc.appspot.com',
    measurementId: 'G-R0LM61G6BX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_ZVPyMdsWFhpZI5dbKih3xWNgXWM2OAY',
    appId: '1:652753902156:android:b629024bc4d6d46e8bb2e9',
    messagingSenderId: '652753902156',
    projectId: 'nusliving-a83dc',
    storageBucket: 'nusliving-a83dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyyrPcdsTQzIGHjA6AW2AL5piBJ93NT6Q',
    appId: '1:652753902156:ios:348718e77338cc3b8bb2e9',
    messagingSenderId: '652753902156',
    projectId: 'nusliving-a83dc',
    storageBucket: 'nusliving-a83dc.appspot.com',
    iosClientId: '652753902156-skc3i3jd3vt7qgsh3lcrfrpfrk4rvuc6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyyrPcdsTQzIGHjA6AW2AL5piBJ93NT6Q',
    appId: '1:652753902156:ios:e20a345746d36a1e8bb2e9',
    messagingSenderId: '652753902156',
    projectId: 'nusliving-a83dc',
    storageBucket: 'nusliving-a83dc.appspot.com',
    iosClientId: '652753902156-ps1aub68596og5r787po0dnq87utvnj2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
